name: mabrook
description: A new Flutter project.

publish_to: 'none'

version: 1.0.1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.3
  intl: ^0.17.0
  shared_preferences: ^2.0.6
  flutter_bloc: ^8.0.1
  provider: ^6.0.2
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^9.5.2
  velocity_x: ^3.3.0
  crypto: ^3.0.2
  another_flushbar: ^1.10.28
  qr_code_scanner: ^0.7.0
  scan: ^1.6.0
  image_picker: ^0.8.5+3
  flutter_svg: ^0.22.0
  cached_network_image: ^3.1.0
  uni_links: ^0.5.1
  package_info_plus: ^1.0.6
  permission_handler: ^9.2.0
  dio: ^4.0.6
  path_provider: ^2.0.9
  downloads_path_provider_28: ^0.1.2
  open_file: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  image_path: "assets/images/mask_group_1.png"
  ios: true
  android: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/

